######################################################################
# Automatically generated by qmake (2.01a) ven. mars 25 14:24:51 2011
######################################################################

TEMPLATE = app
TARGET = 
QT += network
QT += xml
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += messages.h socket.h
SOURCES += messages.cpp socket.cpp \
    main.cpp
