######################################################################
# Automatically generated by qmake (2.01a) ven. mars 25 16:22:55 2011
######################################################################

TEMPLATE = app
TARGET = 
QT+=network
QT+=xml
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += clientmanager.h server.h socket.h
SOURCES += clientmanager.cpp server.cpp socket.cpp \
    main.cpp
